version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: weekly
      open-pull-requests-limit: 10
      versioning-strategy: increase
      groups:
        production-dependencies:
          dependency-type: "production"
        development-dependencies:
          dependency-type: "development"
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: weekly
      groups:
        github-actions:
          patterns:
            - "*"
